export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const GET_PRODUCTS_FROM_CART = "GET_PRODUCTS_FROM_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
