export const CREATE_REVIEW = "CREATE_REVIEW";
export const GET_ALL_REVIEW = "GET_ALL_REVIEW";
export const GET_PRODUCT_REVIEW = "GET_PRODUCT_REVIEW";
export const GET_USER_REVIEW = "GET_USER_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
