export const CREATE_ORDER = "CREATE_ORDER";
export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const GET_USER_ORDER = "GET_USER_ORDER";
export const GET_USER_ORDER_BY_ID = "GET_USER_ORDER_BY_ID";
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const DELETE_ORDER = "DELETE_ORDER";
