export const UPDATE_USER = "UPDATE_USER";
export const CHANGE_ROLE_USER = "CHANGE_ROLE_USER";
export const GET_ALL_USER = "GET_ALL_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
