export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const SEARCH_PRODUCT_BY_CATEGORY = "SEARCH_PRODUCT_BY_CATEGORY";
export const SEARCH_PRODUCT_BY_BRAND = "SEARCH_PRODUCT_BY_BRAND";
